"""Publishable graph snapshots and the freshness check that keeps them honest.

The setup site ships ``setup/graph-data.js``: RepoBrain's index of its own
repository, exported for the browser. That artifact is generated by hand, so it
decays silently as the codebase moves. :func:`snapshot_drift` re-indexes the
repository and compares the result against a published snapshot so CI can fail
on staleness instead of discovering it in an audit.

History-derived edges are excluded from the comparison: ``CO_CHANGED_WITH`` is
computed from git history, so it changes with every commit and would make a
correct snapshot look stale one commit after it was generated.
"""
from __future__ import annotations

import json
from pathlib import Path
import sqlite3
import subprocess
import tempfile
from datetime import date

from ..graph.store import GraphStore
from ..indexing.indexer import Indexer

SNAPSHOT_PREFIX = "window.REPOBRAIN_GRAPH = "

#: Edge types derived from git history rather than from the working tree.
HISTORY_EDGE_TYPES = frozenset({"CO_CHANGED_WITH"})


def graph_payload(
    database: str | Path,
    *,
    source: str | None = None,
    commit: str | None = None,
    generated_at: str | None = None,
) -> dict:
    """Read a graph database into a browser-safe, JSON-serializable payload."""
    with sqlite3.connect(database) as connection:
        connection.row_factory = sqlite3.Row
        nodes = [
            dict(row)
            for row in connection.execute(
                """
                SELECT id, type, name, qualified_name, path, start_line, end_line,
                       language, confidence
                FROM nodes ORDER BY type, path, start_line, name
                """
            )
        ]
        node_ids = {node["id"] for node in nodes}
        edges = [
            dict(row)
            for row in connection.execute(
                """
                SELECT source_node_id AS source, target_node_id AS target, type,
                       path, start_line, confidence, is_inferred
                FROM edges ORDER BY type, path, start_line
                """
            )
            if row["source"] in node_ids and row["target"] in node_ids
        ]

    return {
        "generated_from": source if source is not None else str(database),
        "commit": commit,
        "generated_at": generated_at,
        "nodes": nodes,
        "edges": edges,
    }


def write_snapshot(payload: dict, output: str | Path) -> None:
    """Write a payload as the assignment ``setup/graph.html`` loads."""
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        SNAPSHOT_PREFIX
        + json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )


def read_snapshot(path: str | Path) -> dict:
    """Parse a written snapshot back into its payload."""
    source = Path(path).read_text(encoding="utf-8").strip()
    if not source.startswith(SNAPSHOT_PREFIX) or not source.endswith(";"):
        raise ValueError(f"unexpected snapshot format: {path}")
    payload = json.loads(source[len(SNAPSHOT_PREFIX):-1])
    if not isinstance(payload, dict):
        raise ValueError(f"snapshot must contain an object: {path}")
    nodes, edges = payload.get("nodes"), payload.get("edges")
    if not isinstance(nodes, list) or not isinstance(edges, list):
        raise ValueError(f"snapshot must contain node and edge lists: {path}")
    return payload


def structural_counts(payload: dict) -> dict[str, int]:
    """Count the parts of a payload that depend only on the working tree."""
    nodes = payload["nodes"]
    edges = payload["edges"]
    return {
        "files": sum(node["type"] == "File" for node in nodes),
        "nodes": len(nodes),
        "structural_edges": sum(
            edge["type"] not in HISTORY_EDGE_TYPES for edge in edges
        ),
    }


def index_repository_payload(
    root: str | Path,
    *,
    database: str | Path | None = None,
    source: str | None = None,
    commit: str | None = None,
    generated_at: str | None = None,
) -> dict:
    """Index ``root`` from scratch and return its exportable payload.

    Indexing into a throwaway database (rather than reading whatever sits in
    ``.repobrain/``) keeps the published snapshot a function of the tree alone.
    """
    repository = Path(root).resolve()
    with tempfile.TemporaryDirectory(prefix="repobrain-snapshot-") as temp_dir:
        path = Path(database) if database else Path(temp_dir) / "repobrain.sqlite"
        with GraphStore(path) as store:
            Indexer(store).index(repository, incremental=False)
        return graph_payload(
            path,
            source=source if source is not None else "self-index of the working tree",
            commit=commit,
            generated_at=generated_at,
        )


def snapshot_drift(root: str | Path, payload: dict) -> dict[str, tuple[int, int]]:
    """Compare a published snapshot against a fresh index of ``root``.

    Returns ``{metric: (published, measured)}`` for every metric that differs;
    an empty mapping means the snapshot is current.
    """
    published = structural_counts(payload)
    measured = structural_counts(index_repository_payload(root))
    return {
        metric: (published[metric], value)
        for metric, value in measured.items()
        if published[metric] != value
    }


def head_commit(root: str | Path) -> str | None:
    """Return the short HEAD hash, or ``None`` outside a usable git checkout."""
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(root),
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return None
    return completed.stdout.strip() or None if completed.returncode == 0 else None


def refresh_snapshot(root: str | Path, output: str | Path) -> dict[str, int]:
    """Regenerate a repository's published snapshot; return its counts."""
    repository = Path(root).resolve()
    payload = index_repository_payload(
        repository,
        commit=head_commit(repository),
        generated_at=date.today().isoformat(),
    )
    write_snapshot(payload, output)
    return structural_counts(payload)
